# Generated by Django 5.0.3 on 2024-06-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_catagory_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('category_description', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.category'),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
