# Generated by Django 5.0.3 on 2024-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
    ]
